### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by mohnish** [mohnish/money#36]
- [x] reduce the content of each bill on the bills page. this data is already available in the show bill page, so it should be fine. keep only the pieces of info that's absolutely necessary. https://github.com/mohnish/money/issues/38
- [x] update the position of the condensed bills to make 'em look as if they're aligned with the form https://github.com/mohnish/money/issues/49
- [x] selecting never on bills form should display select card on the form https://github.com/mohnish/money/issues/32
- [x] collapse the bills form by default https://github.com/mohnish/money/issues/41
- [x] collapse the payments form by default https://github.com/mohnish/money/issues/42
- [x] update the next_due_date on creation of payment (based on the repetition interval) https://github.com/mohnish/money/issues/43
- [x] turn off autocomplete for some of the fields (needs review) https://github.com/mohnish/money/issues/44
- [x] auto lowercase the username field (autocapitalize="off" on the text field) https://github.com/mohnish/money/issues/45
- [x] the date should always default to todays date https://github.com/mohnish/money/issues/46
